name: auto_commit

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2

      - name: Run a multi-line script
        run: |
          touch test.txt
      - uses: EndBug/add-and-commit@v9
        with:
          add: 'test.txt'
          message: 'test'
          author_name: 'bot'
          author_email: 'test@example.com'
